### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'decimal' in undefined

### ISSUE THREAD

**Issue by heartacker** [mateuszchudyk/vscode-hexinspector#10]
```
[2021-11-27 00:00:34.332] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heart\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.2.0\out\extension.js:27:26)
    at o.provideHover (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:90894)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:114943
    at xe._withAdapter (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:111762)
    at xe.$provideHover (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:114921)
    at t._doInvokeHandler (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
    at t._invokeHandler (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
    at t._receiveRequest (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12097)
    at t._receiveOneMessage (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18929)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34324
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18929)
    at n._receiveMessage (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23321)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21005
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at _.acceptChunk (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15757)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14887
    at Socket.I (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2021-11-27 00:01:06.230] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heart\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.2.0\out\extension.js:27:26)
    at o.provideHover (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:90894)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:114943
    at xe._withAdapter (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:111762)
    at xe.$provideHover (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:114921)
    at t._doInvokeHandler (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
    at t._invokeHandler (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
    at t._receiveRequest (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12097)
    at t._receiveOneMessage (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18929)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34324
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at r.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18929)
    at n._receiveMessage (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23321)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21005
    at a.fire (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
    at _.acceptChunk (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15757)
    at d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14887
    at Socket.I (d:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mateuszchudyk** [comment]
Could you provide a part of your settings.json file corresponding with hexinspector extension?

**Comment by heartacker** [comment]
what is the problem
```log
[2022-07-07 09:41:32.715] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heartacker\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.3.0\out\extension.js:27:26)
    at l.provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40222)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69849
    at te._withAdapter (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:66659)
    at te.$provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69825)
    at s._doInvokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
    at s._invokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
    at s._receiveRequest (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12107)
    at s._receiveOneMessage (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at MessagePortMain.<anonymous> (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32714)
    at MessagePortMain.emit (node:events:390:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_node_init:5:364)
[2022-07-07 09:41:38.622] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heartacker\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.3.0\out\extension.js:27:26)
    at l.provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40222)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69849
    at te._withAdapter (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:66659)
    at te.$provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69825)
    at s._doInvokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
    at s._invokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
    at s._receiveRequest (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12107)
    at s._receiveOneMessage (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at MessagePortMain.<anonymous> (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32714)
    at MessagePortMain.emit (node:events:390:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_node_init:5:364)
[2022-07-07 09:41:39.656] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heartacker\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.3.0\out\extension.js:27:26)
    at l.provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40222)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69849
    at te._withAdapter (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:66659)
    at te.$provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69825)
    at s._doInvokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
    at s._invokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
    at s._receiveRequest (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12107)
    at s._receiveOneMessage (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at MessagePortMain.<anonymous> (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32714)
    at MessagePortMain.emit (node:events:390:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_node_init:5:364)
[2022-07-07 09:41:46.078] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heartacker\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.3.0\out\extension.js:27:26)
    at l.provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40222)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69849
    at te._withAdapter (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:66659)
    at te.$provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69825)
    at s._doInvokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
    at s._invokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
    at s._receiveRequest (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12107)
    at s._receiveOneMessage (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at MessagePortMain.<anonymous> (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32714)
    at MessagePortMain.emit (node:events:390:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_node_init:5:364)
[2022-07-07 09:41:50.098] [renderer1] [error] Cannot use 'in' operator to search for 'decimal' in undefined: TypeError: Cannot use 'in' operator to search for 'decimal' in undefined
    at Object.provideHover (c:\Users\heartacker\.vscode-insiders\extensions\mateuszchudyk.hexinspector-1.3.0\out\extension.js:27:26)
    at l.provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40222)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69849
    at te._withAdapter (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:66659)
    at te.$provideHover (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:69825)
    at s._doInvokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13708)
    at s._invokeHandler (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13390)
    at s._receiveRequest (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12107)
    at s._receiveOneMessage (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10853)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8957
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:34679
    at w.invoke (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at p.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at a.fire (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:18976)
    at MessagePortMain.<anonymous> (d:\Users\heartacker\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:32714)
    at MessagePortMain.emit (node:events:390:28)
    at MessagePortMain.emit (node:domain:475:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_node_init:5:364)
```

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/177672207-9d840f6e-c632-4be4-a344-7c3078d45860.png)

**Comment by mateuszchudyk** [comment]
Please provide:
- version of used extension.
- part of your settings.json file corresponding with the extension.
- input value.

**Comment by heartacker** [comment]
1. 名称: HexInspector
ID: mateuszchudyk.hexinspector
说明: Provides fast and easy way to peek other forms of a hexadecimal/decimal/binary value
版本: 1.3.0
发布者: Mateusz Chudyk
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=mateuszchudyk.hexinspector

2. setting is all by default
3. I do not konw what is input, if i hover to any txt,the error will occur

**Comment by mateuszchudyk** [comment]
Version [1.4.0 ](https://github.com/mateuszchudyk/vscode-hexinspector/releases/tag/v1.4.0) probably fixes this issue.
